# Generated by Django 5.1 on 2024-09-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0017_remove_systemsettings_time_to_dispense_water_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='flow_speed',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dispensing_time_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='speed_value_index',
            field=models.IntegerField(default=0),
        ),
    ]
