# Generated by Django 5.1 on 2024-09-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0018_remove_systemsettings_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='dispensing_time_index',
            new_name='dispensing_time',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='speed_value_index',
            new_name='speed_value',
        ),
    ]
