# Generated by Django 5.1 on 2024-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0019_rename_dispensing_time_index_systemsettings_dispensing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
