# Generated by Django 5.1 on 2024-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0021_remove_systemstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='operational_state',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Maintenance Required', 'Maintenance Required')], default='Normal', max_length=50, null=True),
        ),
    ]
